<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div><h2>Дегтярев Владимир</h2></div>
<div><h3>Группа: ИКБО-01-20</h3></div>
<div><h4>Вариант 6: Создать класс Post с полями text, creationDate.
        <br>
        Создать класс User с
        полями firstName, lastName, middleName, birthDate.
        <br>
        Создать классы контроллеры для создания, удаления объектов и
        получения всех объектов
        каждого типа. Сами объекты хранить в памяти</h4>
</div>

<br>
<br>

<a href="posts">Posts</a>
<br>
<a href="users">Users</a>
</body>
</html>